/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */

#include <user_storage_queries/sql_queries.hpp>

namespace user_storage_queries::sql {

// Generated from create_user.sql
const USERVER_NAMESPACE::storages::Query kCreateUser = {
R"-(
-- Insert data into 'internview_schema.users'
INSERT INTO internview_schema.users(id, login, password_hash, name, role, description, profile_pic)
    VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING
    created_at

)-",
    USERVER_NAMESPACE::storages::Query::NameLiteral("create_user"),
    USERVER_NAMESPACE::storages::Query::LogMode::kFull,
};


}  // namespace user_storage_queries::sql
