/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */

#include <user_storage_queries/sql_queries.hpp>

namespace user_storage_queries::sql {

// Generated from change_user_password.sql
const USERVER_NAMESPACE::storages::Query kChangeUserPassword = {
R"-(
-- Update rows in 'internview_schema.users' where condition is met
UPDATE
    internview_schema.users
SET
    password_hash = $2
WHERE
    id = $1
RETURNING
    id

)-",
    USERVER_NAMESPACE::storages::Query::NameLiteral("change_user_password"),
    USERVER_NAMESPACE::storages::Query::LogMode::kFull,
};




// Generated from create_user.sql
const USERVER_NAMESPACE::storages::Query kCreateUser = {
R"-(
-- Insert data into 'internview_schema.users'
INSERT INTO internview_schema.users(id, login, password_hash, name, role, description, profile_pic)
    VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (login)
    DO NOTHING
RETURNING
    created_at

)-",
    USERVER_NAMESPACE::storages::Query::NameLiteral("create_user"),
    USERVER_NAMESPACE::storages::Query::LogMode::kFull,
};




// Generated from delete_user.sql
const USERVER_NAMESPACE::storages::Query kDeleteUser = {
R"-(
-- Delete rows from 'internview_schema.users' where condition is met
DELETE FROM internview_schema.users
WHERE id = $1
RETURNING
    id

)-",
    USERVER_NAMESPACE::storages::Query::NameLiteral("delete_user"),
    USERVER_NAMESPACE::storages::Query::LogMode::kFull,
};




// Generated from get_user_by_id.sql
const USERVER_NAMESPACE::storages::Query kGetUserById = {
R"-(
-- Select all rows from 'internview_schema.users'
SELECT
    *
FROM
    internview_schema.users
WHERE
    id = $1

)-",
    USERVER_NAMESPACE::storages::Query::NameLiteral("get_user_by_id"),
    USERVER_NAMESPACE::storages::Query::LogMode::kFull,
};




// Generated from login_user.sql
const USERVER_NAMESPACE::storages::Query kLoginUser = {
R"-(
-- Select all rows from 'internview_schema.users'
SELECT
    *
FROM
    internview_schema.users
WHERE
    login = $1

)-",
    USERVER_NAMESPACE::storages::Query::NameLiteral("login_user"),
    USERVER_NAMESPACE::storages::Query::LogMode::kFull,
};




// Generated from update_user.sql
const USERVER_NAMESPACE::storages::Query kUpdateUser = {
R"-(
-- Update rows in 'internview_schema.users' where condition is met
UPDATE
    internview_schema.users
SET
    login = $1,
    name = $2,
    description = $3,
    profile_pic = $4
WHERE
    id = $5 AND NOT EXISTS (
        SELECT 1 FROM internview_schema.users
        WHERE login = $1 AND id != $5
    )

RETURNING
    id


)-",
    USERVER_NAMESPACE::storages::Query::NameLiteral("update_user"),
    USERVER_NAMESPACE::storages::Query::LogMode::kFull,
};


}  // namespace user_storage_queries::sql
