/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */

#include <vacancy_application_queries/sql_queries.hpp>

namespace vacancy_application_queries::sql {

// Generated from create_application.sql
const USERVER_NAMESPACE::storages::Query kCreateApplication = {
R"-(
-- Insert data into 'internview_schema.applications'
INSERT INTO internview_schema.applications(id, vacancy_id, intern_id, cv_id, cover_letter)
    VALUES ($1, $2, $3, $4, $5)
RETURNING
    *;


)-",
    USERVER_NAMESPACE::storages::Query::NameLiteral("create_application"),
    USERVER_NAMESPACE::storages::Query::LogMode::kFull,
};


}  // namespace vacancy_application_queries::sql
