# THIS FILE IS AUTOGENERATED, DON'T EDIT!

import pytest


@pytest.fixture(scope='session')
def sql_files() -> set:
    return set([
        # Generated from check_intern_applied.sql
        "check_intern_applied",
    
        # Generated from create_application.sql
        "create_application",
    
        # Generated from delete_application.sql
        "delete_application",
    
        # Generated from get_application_by_id.sql
        "get_application_by_id",
    
        # Generated from get_intern_id_by_cv.sql
        "get_intern_id_by_cv",
    
        # Generated from get_interns_applications.sql
        "get_interns_applications",
    
        # Generated from get_recruiter_applications.sql
        "get_recruiter_applications",
    
        # Generated from get_vacancy_applications.sql
        "get_vacancy_applications",
    
        # Generated from update_application.sql
        "update_application",
    ])
