/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */

#include <cv_storage_queries/sql_queries.hpp>

namespace cv_storage_queries::sql {

// Generated from create_cv.sql
const USERVER_NAMESPACE::storages::Query kCreateCv = {
    R"-(
-- Insert data into 'internview_schema.cvs'
INSERT INTO internview_schema.cvs(id, user_id, title, description, cv_pdf)
    VALUES ($1, $2, $3, $4, $5)
RETURNING
    created_at

)-",
    USERVER_NAMESPACE::storages::Query::NameLiteral("create_cv"),
    USERVER_NAMESPACE::storages::Query::LogMode::kFull,
};

// Generated from delete_cv.sql
const USERVER_NAMESPACE::storages::Query kDeleteCv = {
    R"-(
-- Delete rows from 'internview_schema.cvs' where condition is met
DELETE FROM internview_schema.cvs
WHERE id = $1
    AND user_id = $2
RETURNING
    id

)-",
    USERVER_NAMESPACE::storages::Query::NameLiteral("delete_cv"),
    USERVER_NAMESPACE::storages::Query::LogMode::kFull,
};

// Generated from get_cv_by_id.sql
const USERVER_NAMESPACE::storages::Query kGetCvById = {
    R"-(
-- Select all rows from 'internview_schema.cvs'
SELECT
    *
FROM
    internview_schema.cvs
WHERE
    id = $1
    AND user_id = $2;


)-",
    USERVER_NAMESPACE::storages::Query::NameLiteral("get_cv_by_id"),
    USERVER_NAMESPACE::storages::Query::LogMode::kFull,
};

// Generated from get_cvs.sql
const USERVER_NAMESPACE::storages::Query kGetCvs = {
    R"-(
-- Select all rows from 'internview_schema.cvs'
SELECT
    *
FROM
    internview_schema.cvs
WHERE
    user_id = $1;


)-",
    USERVER_NAMESPACE::storages::Query::NameLiteral("get_cvs"),
    USERVER_NAMESPACE::storages::Query::LogMode::kFull,
};

// Generated from update_cv.sql
const USERVER_NAMESPACE::storages::Query kUpdateCv = {
    R"-(
-- Update rows in 'internview_schema.cvs' where condition is met
UPDATE
    internview_schema.cvs
SET
    title = $2,
    description = $3,
    cv_pdf = $4,
    updated_at = NOW()
WHERE
    id = $1
RETURNING
    updated_at

)-",
    USERVER_NAMESPACE::storages::Query::NameLiteral("update_cv"),
    USERVER_NAMESPACE::storages::Query::LogMode::kFull,
};

}  // namespace cv_storage_queries::sql
