/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */

#include <cv_storage_queries/sql_queries.hpp>

namespace cv_storage_queries::sql {

// Generated from create_cv.sql
const USERVER_NAMESPACE::storages::Query kCreateCv = {
R"-(
-- Insert data into 'internview_schema.cv'
INSERT INTO internview_schema.cv(id, user_id, title, description, cv_pdf)
    VALUES ($1, $2, $3, $4, $5)
RETURNING
    created_at

)-",
    USERVER_NAMESPACE::storages::Query::NameLiteral("create_cv"),
    USERVER_NAMESPACE::storages::Query::LogMode::kFull,
};


}  // namespace cv_storage_queries::sql
