# THIS FILE IS AUTOGENERATED, DON'T EDIT!

import pytest


@pytest.fixture(scope='session')
def sql_files() -> set:
    return set([
        # Generated from clear_expired_tokens.sql
        "clear_expired_tokens",
    
        # Generated from create.sql
        "create",
    
        # Generated from delete.sql
        "delete",
    
        # Generated from get_by_token_hash.sql
        "get_by_token_hash",
    
        # Generated from revoke.sql
        "revoke",
    
        # Generated from revoke_all_user_tokens.sql
        "revoke_all_user_tokens",
    ])
