#pragma once

/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */

#include <userver/storages/query.hpp>

namespace user_storage_queries::sql {


// Generated from create_user.sql
extern const USERVER_NAMESPACE::storages::Query kCreateUser;

}  // namespace user_storage_queries::sql
