/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */

#include <vacancy_storage_queries/sql_queries.hpp>

namespace vacancy_storage_queries::sql {

// Generated from create_vacancy.sql
const USERVER_NAMESPACE::storages::Query kCreateVacancy = {
R"-(
INSERT INTO internview_schema.vacancies(id, recruiter_id, title, description, requirements, salary_range, location, work_mode, experience_level)
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT
    DO NOTHING
RETURNING
    *;


)-",
    USERVER_NAMESPACE::storages::Query::NameLiteral("create_vacancy"),
    USERVER_NAMESPACE::storages::Query::LogMode::kFull,
};


}  // namespace vacancy_storage_queries::sql
