/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */

#include <vacancy_storage_queries/sql_queries.hpp>

namespace vacancy_storage_queries::sql {

// Generated from create_vacancy.sql
const USERVER_NAMESPACE::storages::Query kCreateVacancy = {
R"-(
INSERT INTO internview_schema.vacancies(id, recruiter_id, title, description, requirements, salary_range, location, work_mode, experience_level)
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING
    *;


)-",
    USERVER_NAMESPACE::storages::Query::NameLiteral("create_vacancy"),
    USERVER_NAMESPACE::storages::Query::LogMode::kFull,
};




// Generated from get_recruiter_vacancies.sql
const USERVER_NAMESPACE::storages::Query kGetRecruiterVacancies = {
R"-(
-- Select all rows from 'internview_schema.vacancies'
SELECT
    *
FROM
    internview_schema.vacancies
WHERE
    recruiter_id = $1;


)-",
    USERVER_NAMESPACE::storages::Query::NameLiteral("get_recruiter_vacancies"),
    USERVER_NAMESPACE::storages::Query::LogMode::kFull,
};




// Generated from get_vacancies.sql
const USERVER_NAMESPACE::storages::Query kGetVacancies = {
R"-(
-- Select all rows from 'internview_schema.vacancies'
SELECT
    *
FROM
    internview_schema.vacancies
WHERE
    is_active = TRUE
ORDER BY
    created_at DESC
LIMIT $1 OFFSET $2;


)-",
    USERVER_NAMESPACE::storages::Query::NameLiteral("get_vacancies"),
    USERVER_NAMESPACE::storages::Query::LogMode::kFull,
};




// Generated from get_vacancy_by_id.sql
const USERVER_NAMESPACE::storages::Query kGetVacancyById = {
R"-(
-- Select all rows from 'internview_schema.vacancies'
SELECT
    *
FROM
    internview_schema.vacancies
WHERE
    id = $1;


)-",
    USERVER_NAMESPACE::storages::Query::NameLiteral("get_vacancy_by_id"),
    USERVER_NAMESPACE::storages::Query::LogMode::kFull,
};




// Generated from update_vacancy.sql
const USERVER_NAMESPACE::storages::Query kUpdateVacancy = {
R"-(
-- Update rows in 'internview_schema.vacancies' where condition is met
UPDATE
    internview_schema.vacancies
SET
    title = $2,
    description = $3,
    requirements = $4,
    salary_range = $5,
    location = $6,
    work_mode = $7,
    experience_level = $8,
    updated_at = NOW()
WHERE
    id = $1
RETURNING
    id;


)-",
    USERVER_NAMESPACE::storages::Query::NameLiteral("update_vacancy"),
    USERVER_NAMESPACE::storages::Query::LogMode::kFull,
};


}  // namespace vacancy_storage_queries::sql
