#pragma once

/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */

#include <userver/storages/query.hpp>

namespace vacancy_application_queries::sql {


// Generated from create_application.sql
extern const USERVER_NAMESPACE::storages::Query kCreateApplication;

}  // namespace vacancy_application_queries::sql
