/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */

#include <application_storage_queries/sql_queries.hpp>

namespace application_storage_queries::sql {

// Generated from check_intern_applied.sql
const USERVER_NAMESPACE::storages::Query kCheckInternApplied = {
R"-(
SELECT
    1
FROM
    internview_schema.applications
WHERE
    intern_id = $1
    AND vacancy_id IN (
        SELECT
            id
        FROM
            internview_schema.vacancies
        WHERE
            recruiter_id = $2);


)-",
    USERVER_NAMESPACE::storages::Query::NameLiteral("check_intern_applied"),
    USERVER_NAMESPACE::storages::Query::LogMode::kFull,
};




// Generated from create_application.sql
const USERVER_NAMESPACE::storages::Query kCreateApplication = {
R"-(
-- Insert data into 'internview_schema.applications'
INSERT INTO internview_schema.applications(id, vacancy_id, intern_id, cv_id, cover_letter)
    VALUES ($1, $2, $3, $4, $5)
RETURNING
    *;


)-",
    USERVER_NAMESPACE::storages::Query::NameLiteral("create_application"),
    USERVER_NAMESPACE::storages::Query::LogMode::kFull,
};




// Generated from delete_application.sql
const USERVER_NAMESPACE::storages::Query kDeleteApplication = {
R"-(
-- Delete rows from 'internview_schema.applications' where condition is met
DELETE FROM internview_schema.applications
WHERE id = $1
    AND intern_id = $2
RETURNING
    id;


)-",
    USERVER_NAMESPACE::storages::Query::NameLiteral("delete_application"),
    USERVER_NAMESPACE::storages::Query::LogMode::kFull,
};




// Generated from get_application_by_id.sql
const USERVER_NAMESPACE::storages::Query kGetApplicationById = {
R"-(
-- Select all rows from 'internview_schema.applications'
SELECT
    *
FROM
    internview_schema.applications
WHERE
    id = $1;


)-",
    USERVER_NAMESPACE::storages::Query::NameLiteral("get_application_by_id"),
    USERVER_NAMESPACE::storages::Query::LogMode::kFull,
};




// Generated from get_intern_id_by_cv.sql
const USERVER_NAMESPACE::storages::Query kGetInternIdByCv = {
R"-(
SELECT
    intern_id
FROM
    internview_schema.applications
WHERE
    cv_id = $1
    AND vacancy_id IN (
        SELECT
            id
        FROM
            internview_schema.vacancies
        WHERE
            recruiter_id = $2)
LIMIT 1;


)-",
    USERVER_NAMESPACE::storages::Query::NameLiteral("get_intern_id_by_cv"),
    USERVER_NAMESPACE::storages::Query::LogMode::kFull,
};




// Generated from get_interns_applications.sql
const USERVER_NAMESPACE::storages::Query kGetInternsApplications = {
R"-(
-- Select all rows from 'internview_schema.applications'
SELECT * FROM internview_schema.applications
WHERE intern_id = $1;
)-",
    USERVER_NAMESPACE::storages::Query::NameLiteral("get_interns_applications"),
    USERVER_NAMESPACE::storages::Query::LogMode::kFull,
};




// Generated from get_recruiter_applications.sql
const USERVER_NAMESPACE::storages::Query kGetRecruiterApplications = {
R"-(
-- Select all rows from 'internview_schema.applications'
SELECT
    *
FROM
    internview_schema.applications
WHERE
    vacancy_id IN (
        SELECT
            id
        FROM
            internview_schema.vacancies
        WHERE
            recruiter_id = $1);


)-",
    USERVER_NAMESPACE::storages::Query::NameLiteral("get_recruiter_applications"),
    USERVER_NAMESPACE::storages::Query::LogMode::kFull,
};




// Generated from get_vacancy_applications.sql
const USERVER_NAMESPACE::storages::Query kGetVacancyApplications = {
R"-(
-- Select all rows from 'internview_schema.applications'
SELECT
    *
FROM
    internview_schema.applications
WHERE
    vacancy_id = $1;


)-",
    USERVER_NAMESPACE::storages::Query::NameLiteral("get_vacancy_applications"),
    USERVER_NAMESPACE::storages::Query::LogMode::kFull,
};




// Generated from update_application.sql
const USERVER_NAMESPACE::storages::Query kUpdateApplication = {
R"-(
-- Update rows in 'internview_schema.applications' where condition is met
UPDATE
    internview_schema.applications
SET
    cv_id = $2,
    status = $3,
    cover_letter = $4
WHERE
    id = $1
RETURNING
    *;


)-",
    USERVER_NAMESPACE::storages::Query::NameLiteral("update_application"),
    USERVER_NAMESPACE::storages::Query::LogMode::kFull,
};


}  // namespace application_storage_queries::sql
