components_manager:
    task_processors: # Task processor is an executor for coroutine tasks
        main-task-processor: # Make a task processor for CPU-bound coroutine tasks.
            worker_threads: $worker-threads # Process tasks in 4 threads.

        fs-task-processor: # Make a separate task processor for filesystem bound tasks.
            worker_threads: $worker-fs-threads

        crypt-task-processor:
            worker_threads: $worker-crypt-threads

    default_task_processor: main-task-processor

    components: # Configuring components that were registered via component_list
        server:
            listener: # configuring the main listening socket...
                port: $server-port # ...to listen on this port and...
                task_processor: main-task-processor # ...process incoming requests on this task processor.

        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: "@stderr"
                    level: $logger-level
                    overflow_behavior: discard # Drop logs if the system is too busy to write them down.

        # Dynamic config options. Cache is disabled, updates are disabled.
        dynamic-config:
            # For most of userver dynamic configs, defaults are used, some are overridden here.
            # See userver "dynamic config" docs for what configs exist.
            defaults:
                HTTP_CLIENT_CONNECTION_POOL_SIZE: 1000
                POSTGRES_DEFAULT_COMMAND_CONTROL:
                    network_timeout_ms: 750
                    statement_timeout_ms: 500

        testsuite-support: {}

        congestion-control:

        http-client:
        http-client-core:
            load-enabled: $is_testing
            fs-task-processor: fs-task-processor

        dns-client:
            fs-task-processor: fs-task-processor

        tests-control:
            load-enabled: $is-testing
            path: /tests/{action}
            method: POST
            task_processor: main-task-processor

        handler-ping:
            path: /ping
            method: GET
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        postgres-db:
            dbconnection: $pg-connection
            dbconnection#env: DB_CONNECTION
            blocking_task_processor: fs-task-processor
            dns_resolver: async
            sync-start: true
            connlimit_mode: manual

        default-secdist-provider:
            config: /Users/oartemiy/code/internview/configs/secure_data.json
            missing-ok: false
            environment-secrets-key: SECDIST_CONFIG

        internview-component: {}

        handler-status-get:
            path: /status
            method: GET
            task_processor: main-task-processor

        handler-auth-register-post:
            path: /auth/register
            method: POST
            task_processor: main-task-processor

        handler-auth-login-post:
            path: /auth/login
            method: POST
            task_processor: main-task-processor

        handler-auth-change-password-post:
            path: /auth/change-password
            method: POST
            task_processor: main-task-processor

        handler-user-delete:
            path: /users/me
            method: DELETE
            task_processor: main-task-processor

        handler-user-update:
            path: /users/me
            method: PATCH
            task_processor: main-task-processor

        handler-user-get:
            path: /users/me
            method: GET
            task_processor: main-task-processor

        handler-profile-pic-post:
            path: /users/me/profile-pic
            method: POST
            task_processor: main-task-processor
            max_request_size: 5242880

        handler-profile-pic-get:
            path: /users/me/profile-pic
            method: GET
            task_processor: main-task-processor

        # NOTE: while fs-cache does not support mac os

        handler-cv-post:
            path: /cvs
            method: POST
            task_processor: main-task-processor

        handler-cv-get:
            path: /cvs/me
            method: GET
            task_processor: main-task-processor

        handler-cv-get-by-id:
            path: /cvs/{id}
            method: GET
            task_processor: main-task-processor

        handler-cv-update-by:
            path: /cvs/{id}
            method: PATCH
            task_processor: main-task-processor

        handler-cv-delete:
            path: /cvs/{id}
            method: DELETE
            task_processor: main-task-processor

        handler-cv-pdf-post:
            path: /cvs/{id}/pdf
            method: POST
            task_processor: main-task-processor

        handler-cv-pdf-get:
            path: /cvs/{id}/pdf
            method: GET
            task_processor: main-task-processor

        handler-vacancy-post:
            path: /vacancies
            method: POST
            task_processor: main-task-processor

        handler-vacancies-get:
            path: /vacancies
            method: GET
            task_processor: main-task-processor

        handler-vacancies-get-me:
            path: /vacancies/me
            method: GET
            task_processor: main-task-processor

        handler-vacancies-get-by-id:
            path: /vacancies/{id}
            method: GET
            task_processor: main-task-processor
        
        handler-vacancies-update-id:
            path: /vacancies/{id}
            method: PATCH
            task_processor: main-task-processor

        handler-vacancies-delete:
            path: /vacancies/{id}
            method: DELETE
            task_processor: main-task-processor
