#pragma once

/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */

#include <userver/storages/query.hpp>

namespace cv_storage_queries::sql {


// Generated from create_cv.sql
extern const USERVER_NAMESPACE::storages::Query kCreateCv;


// Generated from get_cv_by_id.sql
extern const USERVER_NAMESPACE::storages::Query kGetCvById;


// Generated from get_cvs.sql
extern const USERVER_NAMESPACE::storages::Query kGetCvs;

}  // namespace cv_storage_queries::sql
