#pragma once

/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */

#include <userver/storages/query.hpp>

namespace cv_storage_queries::sql {


// Generated from create_cv.sql
extern const USERVER_NAMESPACE::storages::Query kCreateCv;

}  // namespace cv_storage_queries::sql
