# THIS FILE IS AUTOGENERATED, DON'T EDIT!

import pytest


@pytest.fixture(scope='session')
def sql_files() -> set:
    return set([
        # Generated from create_cv.sql
        "create_cv",
    
        # Generated from get_cv_by_id.sql
        "get_cv_by_id",
    
        # Generated from get_cvs.sql
        "get_cvs",
    
        # Generated from update_cv.sql
        "update_cv",
    ])
