# THIS FILE IS AUTOGENERATED, DON'T EDIT!

import pytest


@pytest.fixture(scope='session')
def sql_files() -> set:
    return set([
        # Generated from create_cv.sql
        "create_cv",
    ])
