# THIS FILE IS AUTOGENERATED, DON'T EDIT!

import pytest


@pytest.fixture(scope='session')
def sql_files() -> set:
    return set([
        # Generated from create_vacancy.sql
        "create_vacancy",
    
        # Generated from get_vacancies.sql
        "get_vacancies",
    ])
