/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */

#include <refresh_token_storage_queries/sql_queries.hpp>

namespace refresh_token_storage_queries::sql {

// Generated from create.sql
const USERVER_NAMESPACE::storages::Query kCreate = {
    R"-(
-- Insert data into 'refresh_tokens'
INSERT INTO internview_schema.refresh_tokens(id, user_id, token_hash, expires_at)
    VALUES ($1, $2, $3, $4);


)-",
    USERVER_NAMESPACE::storages::Query::NameLiteral("create"),
    USERVER_NAMESPACE::storages::Query::LogMode::kFull,
};

// Generated from delete.sql
const USERVER_NAMESPACE::storages::Query kDelete = {
    R"-(
-- Delete rows from 'internview_schema.refresh_tokens' where condition is met
DELETE FROM internview_schema.refresh_tokens
WHERE id = $1;


)-",
    USERVER_NAMESPACE::storages::Query::NameLiteral("delete"),
    USERVER_NAMESPACE::storages::Query::LogMode::kFull,
};

// Generated from get_by_token_hash.sql
const USERVER_NAMESPACE::storages::Query kGetByTokenHash = {
    R"-(
-- Select all rows from 'internview_schema.refresh_tokens'
SELECT
    *
FROM
    internview_schema.refresh_tokens
WHERE
    token_hash = $1;


)-",
    USERVER_NAMESPACE::storages::Query::NameLiteral("get_by_token_hash"),
    USERVER_NAMESPACE::storages::Query::LogMode::kFull,
};

// Generated from revoke.sql
const USERVER_NAMESPACE::storages::Query kRevoke = {
    R"-(
-- Update rows in 'internview_schema.refresh_tokens' where condition is met
UPDATE
    internview_schema.refresh_tokens
SET
    revoked = TRUE
WHERE
    id = $1;


)-",
    USERVER_NAMESPACE::storages::Query::NameLiteral("revoke"),
    USERVER_NAMESPACE::storages::Query::LogMode::kFull,
};

// Generated from revoke_all_user_tokens.sql
const USERVER_NAMESPACE::storages::Query kRevokeAllUserTokens = {
    R"-(
-- Update rows in 'internview_schema.refresh_tokens' where condition is met
UPDATE
    internview_schema.refresh_tokens
SET
    revoked = TRUE
WHERE
    user_id = $1;


)-",
    USERVER_NAMESPACE::storages::Query::NameLiteral("revoke_all_user_tokens"),
    USERVER_NAMESPACE::storages::Query::LogMode::kFull,
};

}  // namespace refresh_token_storage_queries::sql
