# THIS FILE IS AUTOGENERATED, DON'T EDIT!

import pytest


@pytest.fixture(scope='session')
def sql_files() -> set:
    return set([
        # Generated from create_user.sql
        "create_user",
    
        # Generated from delete_user.sql
        "delete_user",
    
        # Generated from get_user_by_id.sql
        "get_user_by_id",
    ])
