#pragma once

/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */

#include <userver/storages/query.hpp>

namespace vacancy_storage_queries::sql {


// Generated from create_vacancy.sql
extern const USERVER_NAMESPACE::storages::Query kCreateVacancy;

}  // namespace vacancy_storage_queries::sql
